[project]
name = "easyrl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.3.3",
    "transformers>=4.57.1",
    "vllm>=0.11.0",
]
